config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :stocks,     only: [:index, :show]
  resources :portfolios
  resources :alerts
  resources :account_activations, only: :edit
end

app/models/stock.rb
class Stock < ApplicationRecord
  self.primary_key = :code
  
  has_many :portfolios, foreign_key: "stock_code",
                        dependent: :destroy
  has_many :users, through: :portfolios
  has_many :alerts, dependent: :destroy

  validates :code, presence: true,
                   uniqueness: true,
                   length: { is: 4 }
                   
  def day_change
    (today_price - yesterday_price) / yesterday_price * 100 
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @q = Stock.ransack(params[:q])

    @stocks = @q.result
                .order("(today_price - yesterday_price) / yesterday_price * 100 desc")
  end

  def show
    @stock = Stock.find(params[:id])
    @tweets = Tweet.list(@stock.name, 5)
  end

  private
    def search_params
      params.require(:q).permit(:code_eq, :name_cont)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/index.html.slim
- @page_title = "銘柄一覧"

.form_container= search_form_for @q do |f|
  = f.label :code_eq, class: "form_label"
  = f.search_field :code_eq, class: "form_input"

  = f.label :name_cont, class: "form_label"
  = f.search_field :name_cont, class: "form_input"

  = f.submit "検索", class: "form_button"

table.stock_index
  caption 銘柄一覧
  thead
    tr
      th
      th 銘柄
      th 終値
      th 前日比
  tbody
    - @stocks.each do |stock|
      tr.main_row
        td.asset_code= stock.code
        td.asset_name= link_to stock.name, stock
        td.asset_price= stock.today_price
        td.asset_change= render "layouts/day_change", day_change: stock.day_change

app/views/stocks/show.html.slim
- @page_title = "#{@stock.code} #{@stock.name}"

div.stock_container

  section.stock_show
    span.asset_code= @stock.code
    h1.asset_name= @stock.name

    span.asset_price= @stock.today_price
    .asset_change= render "layouts/day_change", day_change: @stock.day_change

    - if current_user
      - if current_user.stocks.ids.include?(@stock.code) == false
        = form_with scope: :portfolio, url: portfolios_path, local: true, class: "portfolio_form" do |f|
          = f.hidden_field :stock_code, value: @stock.code
          = f.number_field :holding, class: "holding_field", value: 1
          br
          = f.submit "購入", class: ["button", "add_button"]

      - else
        - portfolio = current_user.portfolios.find_by(stock_code: @stock.code)
        = form_with scope: :portfolio, url: portfolio, method: :patch, local: true, class: "portfolio_form" do |f|
          = f.hidden_field :stock_code, value: @stock.code
          = f.number_field :holding, class: "holding_field", value: portfolio.holding, min: 1
          br
          = f.submit "更新", class: ["button", "update_button"]

        - portfolio = current_user.portfolios.find_by(stock_code: @stock.code)
        = form_with scope: :portfolio, url: portfolio, method: :delete, local: true, class: "portfolio_form" do |f|
          = f.hidden_field :stock_code, value: @stock.code
          = f.hidden_field :holding, value: 0
          br
          = f.submit "全売却", class: ["button", "delete_button"]

    p.asset_updated_at= @stock.updated_at.strftime("%m/%d %H:%M")
    p.provider= link_to "Bloomberg", "https://www.bloomberg.co.jp/quote/#{@stock.code}:JP"
    p.provider= link_to "Yahoo! ファイナンス", "https://stocks.finance.yahoo.co.jp/stocks/detail/?code=#{@stock.code}.T"

  section.stock_tweets
    h2 ツイート
    - @tweets.each do |tweet|
      .tweet
        .tweet_user
          = link_to tweet.user_url, class: "tweet_user_image"
            = image_tag tweet.user_image_url
          span.tweet_user_name
            = link_to tweet.user_name, tweet.user_url
          span.tweet_user_id
            = link_to "@#{tweet.user_id}", tweet.user_url
        p.tweet_text
          = link_to tweet.text, tweet.url
        span.tweet_created_at= tweet.created_at