config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :stocks,     only: [:index, :show]
  resources :portfolios
  resources :alerts
  resources :account_activations, only: :edit
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :activation_token
  has_secure_password

  before_create :create_activation_digest
  after_create :create_wallet_cash

  has_one :wallet, dependent: :destroy
  has_many :portfolios, dependent: :destroy
  has_many :stocks, through: :portfolios
  has_many :alerts, dependent: :destroy

  validates :name, presence: true,
                   uniqueness: true,
                   length: { maximum: 8 }
  validates :email, presence: true,
                    uniqueness: true 
  validates :password, presence: true,
                       length: { minimum: 6 }

  def total_assets
    stocks.sum("today_price * holding") + wallet.cash
  end

  def already_has?(portfolio)
    portfolios.find_by(id: portfolio.id) ? true : false
  end

  def already_has_portfolios_more_than_4?
    portfolios.count > 4
  end

  private
    def create_wallet_cash
      create_wallet
    end

    def create_activation_digest
      self.activation_token = SecureRandom.urlsafe_base64
      self.activation_digest = BCrypt::Password.create(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required, only: :destroy
  before_action :current_user?, only: :destroy

  def index
    @users = User.preload(:stocks, :wallet)
                 .select("users.*, sum(today_price * holding) + avg(distinct cash) as user_total_assets")
                 .joins(:stocks, :wallet)
                 .group("users.id")
                 .order(user_total_assets: :desc, id: :asc)
                 .page(params[:page])
                 .per(10)

    @page_num = params[:page] ? params[:page].to_i : 1
  end

  def show
    @user = User.preload(:stocks, :wallet)
                .find(params[:id])

    if @user.portfolios.count > 0
      @user_rank = User.joins(:stocks, :wallet)
                       .group("users.id")
                       .order( Arel.sql("sum(today_price * holding) + avg(distinct cash) desc"), id: :asc)
                       .ids
                       .index(@user.id) + 1
    else
      @user_rank = "null "
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.activation(@user).deliver_now
      redirect_to root_url, notice: "メールを送信しました"
    else
      flash.now[:alert] = "新規登録に失敗しました"
      render "new"
    end
  end

  def destroy
    if @user.email == "test@example.com"
      redirect_to @user, alert: "テストユーザーは削除できません"
    else
      @user.destroy!
      redirect_to root_url, alert: "アカウントを削除しました"
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
    
    def current_user?
      @user = User.find(params[:id])
      redirect_to root_url unless @user == current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.slim
table.user_index
  caption ユーザーランキング
  thead
    tr
      th
      th 名前
      th 総資産
  tbody
    - @users.each_with_index do |user, index|
      tr.main_row
        td.user_rank= (@page_num - 1) * 10 + (index + 1)
        td.user_name= link_to user.name, user
        td.user_total_assets= "#{user.user_total_assets.to_i} 円"
      tr
        td
        td.user_portfolios colspan=2
          ul
            - user.portfolios.sort_by{|portfolio| portfolio.total_value}.reverse.each do |portfolio|
              li
                span.asset_name= link_to portfolio.stock.name, portfolio.stock
                span.asset_holding= portfolio.holding

                - if portfolio.stock.day_change >= 0
                  span.plus_price.asset_subtotal= "#{(portfolio.total_value).to_i} 円"
                - else
                  span.minus_price.asset_subtotal= "#{(portfolio.total_value).to_i} 円"
            li
              span.asset_name 現金
              span.asset_subtotal= "#{user.wallet.cash.to_i} 円"
    
= paginate @users

app/views/users/new.html.slim
- @page_title = "新規登録"

- if @user.errors.present?
  ul#form_errors
    - @user.errors.full_messages.each do |error|
      li= error

section.form_container
  h1 新規登録
  = form_with model: @user, local: true do |f|
    = f.label :name, "ユーザー名", class: "form_label"
    = f.text_field :name, class: "form_input"

    = f.label :email, "メールアドレス", class: "form_label"
    = f.email_field :email, class: "form_input"

    .password_container
      = f.label :password, "パスワード", class: "form_label"
      = f.password_field :password, class: ["form_input", "password_field"]
      span.password_open 表示

    = f.submit "新規登録", class: "form_button"

app/views/users/show.html.slim
- @page_title = @user.name

.user_header
  .user_name= @user.name
  .user_status
    span= "#{@user_rank}位"
    span= "#{@user.total_assets.to_i} 円"  

div.user_container

  table.user_portfolio
    caption ポートフォリオ
    thead
      tr
        th 
        th 銘柄
        th 
        th 評価額
    tbody
      tr.main_row
        td
        td.asset_name 現金
        td
        td.asset_subtotal.user_cash= "#{@user.wallet.cash.to_i} 円"

      - @user.portfolios.sort_by{|portfolio| portfolio.stock.code}.each do |portfolio|
        = render "portfolios/portfolio", portfolio: portfolio

  - if @user == current_user
    section.user_alert
      h1 アラート
      = form_with scope: :alert, url: alerts_path, class: "alert_form" do |f|
        = f.collection_select :stock_code, @user.stocks.order(:code), :code, :code, id: "alert_stock_code"
        = f.number_field :price, min: 0, step: 0.1, class: "alert_price"
        .yen= "円"
        = f.collection_select :comparison, ["以上", "以下"], :to_s, :to_s, class: "alert_comparison"
        = f.submit "作成", class: ["button", "add_button"]

      table.alert_list
        tbody
          - @user.alerts.each do |alert|
            = render "alerts/alert", alert: alert

- if @user == current_user
  #destroy_container
    span#destroy_open > アカウント削除ボタンを表示
    #destroy_button= link_to "アカウントを削除", @user, method: :delete