config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :stocks,     only: [:index, :show]
  resources :portfolios
  resources :alerts
  resources :account_activations, only: :edit
end

app/models/alert.rb
class Alert < ApplicationRecord
  belongs_to :user
  belongs_to :stock, foreign_key: "stock_code"

  validates :user_id, presence: true
  validates :stock_code, presence: true
  validates :comparison, presence: true
  validates :price, presence: true
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :login_required

  def create
    @alert = current_user.alerts.build(alert_params)

    case @alert.comparison
    when "以上"
      if @alert.stock.today_price >= @alert.price
        redirect_to user_url(current_user), alert: "既に条件を満たしています" and return
      end
    when "以下"
      if @alert.price >= @alert.stock.today_price
        redirect_to user_url(current_user), alert: "既に条件を満たしています" and return
      end
    end

    @alert.save!
  end

  def destroy
    @alert = current_user.alerts.find(params[:id])
    @alert.destroy!
  end

  private
    def alert_params
      params.require(:alert).permit(:stock_code, :comparison, :price)
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_alert.html.slim
tr id="alert-#{alert.id}" class="main_row #{alert.completed}"
  td= link_to "削除", alert_path(alert), method: :delete, remote: true, class: ["button", "delete_button"]
  td= alert.stock_code
  td= "#{alert.price} 円"
  td= alert.comparison
  td= ( alert.completed ? "完了" : "未完了" ) 
  td= alert.updated_at.strftime("%m/%d")

app/views/alerts/create.js.erb
function createAlert() {
  let alert_list = document.querySelector(".alert_list>tbody");
  alert_list.innerHTML += '<%= render "alerts/alert", alert: @alert %>';
}

createAlert();

app/views/alerts/destroy.js.erb
document.querySelector("#alert-<%= @alert.id %>").style.display = "none";