config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :stocks,     only: [:index, :show]
  resources :portfolios
  resources :alerts
  resources :account_activations, only: :edit
end

app/views/layouts/_day_change.html.slim
- if day_change > 0
  span.plus_price= "+#{absolute_value(day_change)}%"
- elsif day_change < 0
  span.minus_price= "-#{absolute_value(day_change)}%"
- else
  span= "#{absolute_value(day_change)}%"

app/views/layouts/_header.html.slim
header
  div#menu_bar 
    div.menu_bar_line
    div.menu_bar_line
    div.menu_bar_line
  nav
    ul#menu_list
      li= link_to "ホーム", root_path
      li= link_to "銘柄一覧", stocks_path
      - if current_user
        li= link_to "マイページ", current_user
        li= link_to "ログアウト", logout_path, method: :delete
      - else
        li= link_to "新規登録", new_user_path
        li= link_to "ログイン", login_path
        li= form_with scope: :session, url: login_url, local: true, id: "test_form" do |f|
            = f.hidden_field :email, value: "test@example.com"
            = f.hidden_field :password, value: "testpass"
            = f.submit "テストログイン", id: "test_button"

  .header_date= header_date

app/views/layouts/application.html.slim
doctype html
html
  head
    title= page_title
    meta charset="utf-8"
    meta name="viewport" content="widht=device-width initial-scale=1"
    = favicon_link_tag
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "layouts/header"
    - if flash[:notice]
      #flash_messages.flash_notice= flash[:notice]
    - if flash[:alert]
      #flash_messages.flash_alert= flash[:alert]
    main
      = yield